export enum ENUM_ROLE_TYPE {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  MENTOR = 'MENTOR',
  CLIENT = 'CLIENT',
}
export enum ENUM_ORDER_STATUS_TYPE {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
